// Every user-facing string of the Remote Hosts feature, keyed by the placeholder keys of the
// slice-4 plan (section 5). Wording is the binding copy table, verbatim; the app has no i18n
// system and this module does not introduce one. `{param}` placeholders are filled by fmt().

export const S = {
  "settings.nav.hosts": "Hosts",
  "hosts.section.title": "Remote hosts",
  "hosts.section.desc": "Connect over SSH to use projects, coding agents, and terminals on other hosts.",
  "hosts.empty.title": "No hosts added",
  "hosts.empty.body": "Add a host using an SSH alias or user@host.",
  "hosts.add": "Add host",
  "hosts.form.titleAdd": "Add host",
  "hosts.form.titleEdit": "Edit host",
  "hosts.form.name.label": "Name",
  "hosts.form.name.placeholder": "Development",
  "hosts.form.sshTarget.label": "SSH target",
  "hosts.form.sshTarget.placeholder": "dev or user@host",
  "hosts.form.sshTarget.help": "Use an alias from ~/.ssh/config or user@host. Key-based SSH is required. First run `ssh <target>` in a terminal to accept the host key.",
  "hosts.form.color.label": "Color",
  "hosts.form.advanced": "Advanced",
  "hosts.form.daemonCommand.label": "Daemon command",
  "hosts.form.daemonCommand.placeholder": "e.g. xshelld",
  "hosts.form.daemonCommand.help": "Optional command to run an existing daemon on the host. xshell appends connect and skips automatic installation and upgrades. Leave blank for managed setup.",
  "hosts.form.launchPrefix.label": "Launch prefixes",
  "hosts.form.launchPrefix.placeholder": "none",
  "hosts.form.launchPrefix.help": "Optional command each agent starts under on this host, such as a wrapper that routes it through a proxy. xshell appends the agent and its arguments. Applies to agents started after you save; shells are not affected.",
  "hosts.form.save": "Save",
  "hosts.form.cancel": "Cancel",
  "hosts.form.err.nameRequired": "Enter a name for this host.",
  "hosts.form.err.targetRequired": "Enter an SSH alias or user@host.",
  "hosts.form.err.targetInvalid": "Enter an SSH alias or user@host: at most 255 characters, no spaces or control characters, and no leading hyphen.",
  "hosts.form.err.commandInvalid": "Enter a non-empty command on one line, or leave it blank.",
  "hosts.form.err.prefixInvalid": "Enter the command on one line and close every quote, or leave it blank.",
  "hosts.row.test": "Test connection",
  "hosts.row.testing": "Testing…",
  "hosts.test.ok": "SSH works · {os} {arch} · xshelld {version}",
  "hosts.test.okNotInstalled": "SSH works. xshell will finish host setup when it connects.",
  "hosts.test.failed": "Connection test failed: {error}",
  "hosts.row.reconnect": "Reconnect now",
  "hosts.row.upgrade": "Upgrade now",
  "hosts.row.upgrading": "Upgrading…",
  "hosts.upgrade.confirmTitle": "Upgrade host setup?",
  "hosts.upgrade.confirmBody": "Upgrading xshell on {host} restarts all {n} terminals, including those used by others. Agent sessions resume; shells start fresh in the same directory.",
  "hosts.upgrade.confirm": "Upgrade now",
  "hosts.row.edit": "Edit",
  "hosts.row.remove": "Remove",
  "hosts.remove.confirmTitle": "Remove host?",
  "hosts.remove.confirmBody": "Remove {host} from xshell? Its projects will be unpinned and its tabs removed here. Terminals keep running on the host.",
  "hosts.remove.confirm": "Remove host",
  "hosts.row.lastError": "Last error",
  "hosts.row.showDetails": "Show details",
  "hosts.row.daemonVersion": "Daemon {v}",
  "hosts.row.desktopVersion": "Desktop {v}",
  "hosts.row.terminals": "Terminals: {n}",
  "hosts.row.agents.title": "Coding agents",
  "hosts.row.agents.unavailable": "Connect to check installed coding agents.",
  "hosts.status.connected": "Connected",
  "hosts.status.reconnecting": "Reconnecting",
  "hosts.status.offline": "Offline",
  "hosts.status.upgradePending": "Upgrade pending",
  "hosts.status.incompatible": "Incompatible",
  "hosts.phase.probing": "Checking…",
  "hosts.phase.installing": "Installing…",
  "hosts.phase.upgrading": "Upgrading…",
  "hosts.status.retryIn": "Retry {s}s",
  "hosts.upgradePending.desc": "xshell {daemon} is running on the host; this Desktop uses {desktop}. Choose Upgrade now to switch, or wait for the next restart.",
  "hosts.incompatible.older": "xshell on this host is too old to connect. Choose Upgrade now.",
  "hosts.incompatible.newer": "xshell on this host needs a newer Desktop. Update xshell on this computer.",
  // Main-session adjustment: `<target>` became a {target} parameter here.
  "hosts.hint.hostKey": "Run `ssh {target}` once in a terminal to accept the key.",
  "hosts.hint.permissionDenied": "Set up SSH key access; verify `ssh -o BatchMode=yes {target}` works.",
  "hosts.hint.unresolved": "Correct the SSH alias or hostname in the host settings.",
  "hosts.hint.unreachable": "Check your network, SSH port, and firewall; ensure SSH is running.",
  "hosts.hint.sshMissing": "Install OpenSSH on this computer and add ssh to PATH.",
  "hosts.hint.unsupportedPlatform": "Use a Linux or macOS host with x86_64 or arm64.",
  "hosts.hint.binaryUnavailable": "Place `xshelld-<platform-triple>` beside the xshell executable, then reconnect.",
  "hosts.hint.daemonCommandFailed": "Fix the advanced command's path or executable permissions on the host.",
  "hosts.hint.xshellNotRunning": "xshell is closed on {target}. Open it there; terminals are reachable only while it's open.",
  "sidebar.project.hostTooltip": "{project} on {host}",
  "sidebar.project.staleTooltip": "{host}: {status}. Project data may be out of date.",
  "picker.group.local": "This computer",
  "picker.group.hostStatus": "{status}",
  "picker.group.stale": "Cached projects",
  "picker.group.empty": "No projects found.",
  "picker.group.neverConnected": "Connect to this host to load its projects.",
  "picker.sub": "Projects from this computer and your configured hosts. The marks on the right show which coding agents have sessions in each project.",
  "picker.addPath.placeholder": "/home/user/project",
  "picker.addPath.button": "Add project",
  "picker.addPath.notFound": "Project path not found. Check that the directory exists on this host.",
  "picker.addPath.offline": "Connect to the host before adding a project path.",
  "terminal.remote.waiting": "Waiting for {host}…",
  "terminal.remote.reconnecting": "Reconnecting to {host}… Input is paused.",
  "terminal.remote.offline": "{host} is offline. Input is paused; xshell will keep retrying.",
  "terminal.remote.incompatible": "Can't connect to {host}. Update xshell on this computer or upgrade xshell on the host.",
  "terminal.remote.inputPaused": "Input is paused until the host reconnects.",
  "terminal.remote.ended": "Ended",
  "terminal.remote.openFailed": "Couldn't start a terminal on {host}: {error}",
  "terminal.local.waiting": "Starting local terminals…",
  "terminal.local.reconnecting": "Reconnecting to local terminals… Input is paused.",
  "terminal.local.offline": "Local terminals are unavailable: {error}. Input is paused; xshell will keep retrying.",
  "terminal.local.openFailed": "Couldn't start a terminal: {error}",
  "terminal.header.hostBadge": "Host: {host}",
  "tab.tooltip.onHost": "On {host}",
  "explorer.row.tooltipRemote": "Drag into the terminal to insert this file's path on the host.",
  "notice.newTerminal.offline": "Can't start a terminal on {host}: {status}. Wait for it to connect or choose Reconnect now in Settings → Hosts.",
  "notice.newTerminal.incompatible": "Can't start a terminal on {host}. Update xshell on this computer or upgrade xshell on the host.",
  "notice.unknownHost": "This host is no longer configured. Add it again in Settings → Hosts.",
  "notice.dismiss": "Dismiss",
  "home.project.stale": "Showing cached project data from {host}. It may be out of date.",
  "home.session.hostBadge": "Host: {host}",
  "agentPicker.titleOnHost": "{project} on {host}",
  "agentPicker.noneOnHost": "No coding agents found on {host}. Install Claude Code, Codex, or another supported CLI on the host.",
  "usage.sourceHost": "Source: {host}",
  "usage.includesHosts": "Hosts: {n}",
  "tab.skipPerms.button.enable": "Skip permissions",
  "tab.skipPerms.button.disable": "Turn off skip permissions",
  "tab.skipPerms.button.busy": "Restarting agent…",
  "tab.skipPerms.disabled.noSession": "No conversation to resume yet.",
  "tab.skipPerms.disabled.ended": "This session has ended.",
  "tab.skipPerms.disabled.hostUnavailable": "{host} is not connected.",
  "tab.skipPerms.confirmEnable.title": "Skip permissions?",
  "tab.skipPerms.confirmEnable.body": "{agent} will run commands and edit files without asking. This interrupts the current run, restarts {agent}, and resumes this conversation.",
  "tab.skipPerms.confirmEnable.confirm": "Skip permissions",
  "tab.skipPerms.confirmDisable.title": "Turn off skip permissions?",
  "tab.skipPerms.confirmDisable.body": "This interrupts the current run, restarts {agent}, and resumes this conversation. {agent} will ask for permission again.",
  "tab.skipPerms.confirmDisable.confirm": "Turn off",
  "tab.skipPerms.cancel": "Cancel",
  "tab.skipPerms.chip": "Skip permissions",
  "tab.skipPerms.chipTooltip": "{agent} runs commands and edits files without asking.",
  "tab.skipPerms.tabTooltip": "Skip permissions is on",
  "tab.skipPerms.restarting": "Restarting {agent}…",
  "tab.skipPerms.failed": "Couldn't change permission settings: {error}",
  "tab.agentStatus.working": "Working",
  "tab.agentStatus.needsYou": "Needs you: waiting for permission or an answer",
  "tab.agentStatus.finished": "Finished: the agent's turn is complete",
  "tab.agentStatus.ended": "Ended: the agent exited",
  "tab.agentStatus.short.working": "Working",
  "tab.agentStatus.short.needsYou": "Needs you",
  "tab.agentStatus.short.finished": "Finished",
  "tab.agentStatus.short.ended": "Ended",
  "tab.agentStatus.stale": "{status} (last known)\n{host} is not connected",
  "tab.agentStatus.aria": "Agent status: {status}",
} as const;

export type StringKey = keyof typeof S;

// `{name}` interpolation. Unknown placeholders are left as-is.
export function fmt(key: StringKey, params?: Record<string, string | number>): string {
  const s: string = S[key];
  if (!params) return s;
  return s.replace(/\{(\w+)\}/g, (m, name: string) => (name in params ? String(params[name]) : m));
}
