[package]
name = "xshell-core"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
portable-pty = { workspace = true }
rusqlite = { workspace = true }
md5 = { workspace = true }

[dev-dependencies]
tempfile = "3"
