// Every user-facing string of Settings → Mobile (#8, #21, pairing #9, removal #22): the binding copy
// tables and the adopted review copy, verbatim. `{param}` placeholders are filled by fmt().

export const S = {
  "settings.nav.mobile": "Mobile",
  "mobile.section.title": "Mobile access",
  "mobile.section.desc": "Watch and control coding agents on your computers from your phone. Traffic is end-to-end encrypted, so the relay can't read it.",
  "mobile.enable": "Enable mobile access",
  "mobile.enabling": "Enabling…",
  "mobile.enable.failed": "Couldn't enable mobile access: {error}",
  "mobile.relay.title": "Relay",
  "mobile.relay.hosted": "Hosted relay",
  "mobile.relay.hosted.desc": "Run by the xshell project. Requires a Hosted subscription purchased in the phone app.",
  "mobile.relay.custom": "Self-hosted relay",
  "mobile.relay.url.label": "Relay URL",
  "mobile.relay.url.placeholder": "wss://relay.example.com",
  "mobile.relay.url.help": "Changing the relay moves all your paired devices to the new URL.",
  "mobile.relay.save": "Use this relay",
  "mobile.relay.err.invalid": "Enter a wss:// URL. Use ws:// only for a loopback address, such as localhost.",
  "mobile.relay.err.saveFailed": "Couldn't change the relay: {error}",
  "mobile.conn.connected": "Connected to the relay",
  "mobile.conn.connecting": "Connecting to the relay…",
  "mobile.conn.retrying": "Can't reach the relay. Retrying in {s}s",
  "mobile.conn.limited": "Connected. To control agents through the hosted relay, purchase a Hosted subscription on one of your paired phones.",
  "mobile.conn.stopped": "This app is no longer one of your paired devices.",
  "mobile.members.title": "Your devices",
  "mobile.member.thisApp": "This app",
  "mobile.member.thisComputer": "This computer",
  "mobile.role.desktop": "Desktop",
  "mobile.role.daemon": "Host",
  "mobile.role.mobile": "Phone",
  "mobile.status.online": "Connected",
  "mobile.status.closed": "xshell closed",
  "mobile.status.unreachable": "Unreachable",
  "mobile.status.never": "Never connected",
  "mobile.status.unknown": "Unknown",
  "mobile.local.inProcess": "Terminals on this computer run inside the app and aren't reachable from your phone.",
  "mobile.local.tooOld": "Local terminal setup doesn't support mobile access. Update xshell on this computer, then reopen it.",
  "mobile.conn.moving": "Telling your paired devices about the new relay…",
  "mobile.conn.moveFailed": "Some paired devices may still use the old relay. xshell keeps trying to reach them.",
  "mobile.conn.otherWindow": "Another xshell window manages the connection to your devices.",
  "mobile.quota.hosted": "Your devices have reached the daily message limit on the hosted relay. The limit resets at {time}; replies and agent output won't reach your phone until then.",
  "mobile.quota.ownRelay": "Your devices have reached the daily message limit on your own relay. The limit resets at {time}; replies and agent output won't reach your phone until then.",
  "mobile.problem.recovered": "Couldn't read your mobile access settings. Saved the old file at {path}. Enable mobile access again, then pair your devices again.",
  "mobile.problem.unreadable": "Couldn't read your mobile access settings. Mobile access is unavailable: {error}",
  "mobile.host.tooOld": "Update xshelld on {name} in Settings → Hosts to make it reachable from your phone.",
  "mobile.host.otherRing": "{name} is paired with another set of devices. Pairing here will end their mobile access to it.",
  "mobile.host.claim": "Pair with this desktop",
  "mobile.host.full": "{name} can't join your devices. You've reached the limit of 64. Remove a device, then try again.",
  "mobile.host.failed": "Couldn't pair {name}: {error}",
  "mobile.pair.phone": "Pair a phone",
  "mobile.pair.phone.desc": "Scan this QR code with the phone app. It works once, for 10 minutes. Can't scan? Copy the pairing text into the phone app.",
  "mobile.pair.phone.expires": "Code expires in {m}:{ss}",
  "mobile.pair.phone.copy": "Copy pairing text",
  "mobile.pair.phone.new": "New code",
  "mobile.pair.expired": "This code expired. Select New code to try again.",
  "mobile.pair.waiting": "Waiting for your phone…",
  "mobile.pair.paired": "Added {name}",
  "mobile.pair.failed": "Couldn't pair the device: {error}",
  "mobile.pair.computer": "Add a computer",
  "mobile.pair.computer.desc": "On the computer you want to add, run `xshelld pair`{relayArg}, then enter the code it shows.",
  "mobile.pair.computer.label": "Pairing code",
  "mobile.pair.computer.placeholder": "XXXX-XXXX-XXXX-XXXX",
  "mobile.pair.computer.connecting": "Looking for the computer…",
  "mobile.pair.computer.notFound": "Couldn't find the computer. Check the code and make sure `xshelld pair` is still running on it.",
  "mobile.pair.computer.invalid": "Enter 16 letters and digits in the form XXXX-XXXX-XXXX-XXXX.",
  "mobile.pair.err.role": "That device can't be added as a computer.",
  "mobile.pair.err.full": "You've reached the limit of 64 devices. Remove a device, then try again.",
  "mobile.pair.connecting": "Connecting to the relay. You can start pairing now. xshell will add the device once it connects.",
  "mobile.pair.needsRelay": "Pairing needs a connection to the relay. xshell keeps trying.",
  "mobile.pair.needsMember": "This app is no longer one of your paired devices, so it can't add devices.",
  "mobile.pair.err.publishFailed": "xshell couldn't reach the relay in time to add the device. Try again.",
  "mobile.member.lastSeen": "Last seen {ago}",
  "mobile.member.remove": "Remove",
  "mobile.member.removing": "Removing…",
  "mobile.remove.confirmTitle": "Remove {name}?",
  "mobile.remove.confirmBody.mobile": "{name} will lose access now, and its open connections to your computers will end. Pair this phone again to add it back.",
  "mobile.remove.confirmBody.daemon": "Phones will no longer be able to reach agents on {name}. Pair this Host again to add it back.",
  "mobile.remove.confirmBody.desktop": "{name} will no longer be able to add or remove devices.",
  "mobile.remove.confirm": "Remove",
  "mobile.remove.failed": "Couldn't remove {name}: {error}",
  "mobile.remove.err.inUse": "This device belongs to a Host in Settings → Hosts. Remove the Host there first.",
  "mobile.remove.err.self": "This app can't remove itself.",
  "mobile.remove.err.otherWindow": "Another xshell window manages mobile access. Remove the device there.",
  "mobile.remove.hostHint": "To remove a Host, remove it in Settings → Hosts first. This computer stays while mobile access is on.",
  "mobile.remove.pending": "{name} was removed here. Other devices will refuse it once xshell reconnects to the relay.",
} as const;

export type StringKey = keyof typeof S;

// `{name}` interpolation. Unknown placeholders are left as-is.
export function fmt(key: StringKey, params?: Record<string, string | number>): string {
  const s: string = S[key];
  if (!params) return s;
  return s.replace(/\{(\w+)\}/g, (m, name: string) => (name in params ? String(params[name]) : m));
}
